var i18n = {};

// ESPAÑOL
i18n.es = 
{
'Gamedev Directory': 'Directorio Gamedev',
'Home': 'Inicio',
'Support': 'Apoyar',
'Contact': 'Contactar',
'Language': 'Idioma',
'Do you want to make a game?': '¿Quieres hacer un videojuego?',
'Dictionary': 'Diccionario',
'Game engines': 'Motores',
'3D Models': 'Modelos 3D',
'Textures and materials': 'Texturas y materiales',
'Music': 'Música',
'Sounds': 'Sonidos',
'Voice over': 'Locuciones',
'Level design': 'Diseño de niveles',
'Interface': 'Interfaces',
'Virtual Reality': 'Realidad Virtual',
'Artificial inteligence': 'Inteligencia Artificial',
'VFX y Shaders': 'VFX y Shaders',
'Organization': 'Organización',
'Accesibility': 'Accesibilidad',
'Do you want to promote your game?': '¿Quieres promocionar tu juego?',
'Self publishing': 'Autopublicación',
'Social media promotion': 'Promoción en redes sociales',
'Video game journalists': 'Periodistas de videojuegos',
'Indie games streamers': 'Streamers de juegos indie',
'Events': 'Eventos',
'Prizes': 'Premios',
'Looking for help?': '¿Buscas ayudas?',
'Financing': 'Financiación',
'Associations': 'Asociaciones',
'Incubators': 'Incubadoras',
'Publishers': 'Publishers',
'Student Discounts': 'Descuentos Estudiantes',
'Do you want to work on it?': '¿Quieres dedicarte a ello?',
'Specialties': 'Especialidades',
'Education': 'Formación',
'Internship': 'Prácticas',
'Jobs': 'Empleo',
'Do you want to meet other people?': '¿Quieres conocer otras personas?',
'Discord Channels': 'Canales Discord',
'Telegram groups': 'Grupos Telegram',
'Looking for inspiration?': '¿Buscas inspiración?',
'Books': 'Libros',
'Podcasts': 'Podcasts',
'Documentaries': 'Documentales',
'Created by': 'Creado por',
'Did you find it useful? ': '¿Te ha parecido útil?',
'Support project': 'Apoyar proyecto',
'Follow @StartGameDev': 'Seguir @StartGameDev',
'Buy a coffee': 'Invitar a un café',
'Share on Twitter': 'Compartir en Twitter',
};



// CATALÀ
i18n.ca = 
{
'Gamedev Directory': 'Directori Gamedev',
'Home': 'Inici',
'Support': 'Suport',
'Contact': 'Contacte',
'Language': 'Idioma',
'Do you want to make a game?': 'Vols fer un videojoc?',
'Dictionary': 'Diccionari',
'Game engines': 'Motors',
'3D Models': 'Models 3D',
'Textures and materials': 'Textures y materials',
'Music': 'Música',
'Sounds': 'Sons',
'Voice over': 'Locucions',
'Level design': 'Disseny de nivells',
'Interface': 'interfícies',
'Virtual Reality': 'Realitat Virtual',
'Artificial inteligence': 'Intel·ligència Artificial',
'VFX y Shaders': 'VFX i Shaders',
'Organization': 'Organització',
'Accesibility': 'Accessibilitat',
'Do you want to promote your game?': 'Vols promocionar el teu joc?',
'Self publishing': 'Autopublicació',
'Social media promotion': 'Promoció a xarxes socials ',
'Video game journalists': 'Periodistes de videojocs ',
'Indie games streamers': 'Streamers de jocs indie',
'Events': 'Esdeveniments',
'Prizes': 'Premis',
'Looking for help?': 'Busques ajudes?',
'Financing': 'Finançament',
'Associations': 'Associacions',
'Incubators': 'Incubadores',
'Publishers': 'Distribuïdors ',
'Student Discounts': 'Descomptes per Estudiants',
'Do you want to work on it?': 'Vols dedicarte a això?',
'Specialties': 'Especialitats',
'Education': 'Formació',
'Internship': 'Pràctiques',
'Jobs': 'Feina',
'Do you want to meet other people?': 'Vols conèixer altres persones?',
'Discord Channels': 'Canales Discord',
'Telegram groups': 'Grups Telegram',
'Looking for inspiration?': 'Busques inspiració?',
'Books': 'Libres',
'Podcasts': 'Podcasts',
'Documentaries': 'Documentals',
'Created by': 'Creat per',
'Did you find it useful? ': 'T\'ha semblat útil?',
'Support project': 'Donar suport',
'Follow @StartGameDev': 'Seguir @StartGameDev',
'Buy a coffee': 'Convidar a un cafè',
'Share on Twitter': 'Compartir a Twitter',
};