var available_langs = ['en', 'es', 'ca', 'it','br'];
var i18n = {};

// ESPAÑOL
i18n.es = 
{
'Gamedev Directory': 'Directorio Gamedev',
'Home': 'Inicio',
'Support': 'Apoyar',
'Contact': 'Contactar',
'Language': 'Idioma',
'Do you want to make a game?': '¿Quieres hacer un videojuego?',
'Dictionary': 'Diccionario',
'Game engines': 'Motores',
'3D Models': 'Modelos 3D',
'Textures and materials': 'Texturas y materiales',
'Music': 'Música',
'Sounds': 'Sonidos',
'Voice over': 'Locuciones',
'Level design': 'Diseño de niveles',
'Interface': 'Interfaces',
'Virtual Reality': 'Realidad Virtual',
'Artificial inteligence': 'Inteligencia Artificial',
'VFX and Shaders': 'VFX y Shaders',
'Organization': 'Organización',
'Accesibility': 'Accesibilidad',
'Do you want to promote your game?': '¿Quieres promocionar tu juego?',
'Self publishing': 'Autopublicación',
'Social media promotion': 'Promoción en redes sociales',
'Video game journalists': 'Periodistas de videojuegos',
'Indie games streamers': 'Streamers de juegos indie',
'Events': 'Eventos',
'Prizes': 'Premios',
'Looking for help?': '¿Buscas ayuda?',
'Financing': 'Financiación',
'Associations': 'Asociaciones',
'Incubators': 'Incubadoras',
'Publishers': 'Publishers',
'Student discounts': 'Descuentos estudiantes',
'Do you want to work on it?': '¿Quieres dedicarte a ello?',
'Specialties': 'Especialidades',
'Education': 'Formación',
'Internship': 'Prácticas',
'Jobs': 'Empleo',
'Do you want to meet other people?': '¿Quieres conocer otras personas?',
'Discord groups': 'Grupos de Discord',
'Telegram groups': 'Grupos de Telegram',
'Looking for inspiration?': '¿Buscas inspiración?',
'Books': 'Libros',
'Podcasts': 'Podcasts',
'Documentaries': 'Documentales',
'Created by': 'Creado por',
'Did you find it useful?': '¿Te ha parecido útil?',
'Support project': 'Apoyar proyecto',
'Follow @StartGameDev': 'Seguir @StartGameDev',
'Buy a coffee': 'Invitar a un café',
'Share on Twitter': 'Compartir en Twitter',
'Name': 'Nombre',
'Price': 'Precio',
'Editable list' : 'Lista editable',
'Information': 'Información',
'List': 'Lista',
'Online course': 'Cursos online',
'Note: There are some affiliate links that will help me maintain the site at no cost to you.': 'Nota: Hay algunos enlaces de afiliado que me ayudarán a mantener la web sin que te cueste demás.',
'Forums': 'Foros',
'Topic': 'Temática',
'Year': 'Año',
'Duration': 'Duración',
'Location': 'Lugar',
'Month': 'Mes',
'Meetings': 'Reuniones',
'Frequency': 'Frecuencia',
'Fairs and conferences': 'Ferias y conferencias',
'Tools': 'Herramientas',
'Directory': 'Directorio',
'Amount': 'Importe',
'Requirements': 'Requisitos',
'View price': 'Ver precio',
'Memory': 'Memoria',
'Resolution': 'Resolución',
'Buy': 'Comprar',
'Photo': 'Foto',
'PC required': 'Requiere PC',
'Store': 'Tienda',
'Mobile and tablets': 'Móviles y tabletas',
'Account cost': 'Coste cuenta',
'Publish cost': 'Coste publicar',
'Platform cut': 'Coste venta',
'Consoles': 'Consolas',
'By contract cannot be published': 'Por contrato no se puede publicar',
'Not available, let me know if you have the data': 'No disponible, házmelo saber si tienes el dato',
'Planification': 'Planificación',
'Documentation': 'Documentación',
'Share files': 'Compartir ficheros',
'Control version': 'Control de versiones',
'Public Domain / Creative Commons / Free': 'De dominio público / Creative Commons / Gratis',
'Other licenses': 'Otras licencias',
'January': 'Enero',
'February': 'Febrero',
'March': 'Marzo',
'April': 'Abril',
'May': 'Mayo',
'June': 'Junio',
'July': 'Julio',
'August': 'Agosto',
'September': 'Septiembre',
'October': 'Octubre',
'November': 'Noviembre',
'December': 'Diciembre',
'Country': 'País',
'Monthly': 'Mensual',
'months': 'meses',
'Interviews': 'Entrevistas',
'Monetization': 'Monetización',
'Multiplayer': 'Multijugador',
'Narrative': 'Narrativa',
'Fonts': 'Fuentes',
'National': 'Nacional',
'Press kit examples': 'Ejemplos de Kit de prensa',
'Title': 'Título',
'Author': 'Autor',
'Translators': 'Traductores',
};



// CATALÀ
i18n.ca = 
{
'Gamedev Directory': 'Directori Gamedev',
'Home': 'Inici',
'Support': 'Suport',
'Contact': 'Contacte',
'Language': 'Idioma',
'Do you want to make a game?': 'Vols fer un videojoc?',
'Dictionary': 'Diccionari',
'Game engines': 'Motors',
'3D Models': 'Models 3D',
'Textures and materials': 'Textures i materials',
'Music': 'Música',
'Sounds': 'Sons',
'Voice over': 'Locucions',
'Level design': 'Disseny de nivells',
'Interface': 'Interfícies',
'Virtual Reality': 'Realitat Virtual',
'Artificial inteligence': 'Intel·ligència Artificial',
'VFX and Shaders': 'VFX i Shaders',
'Organization': 'Organització',
'Accesibility': 'Accessibilitat',
'Do you want to promote your game?': 'Vols promocionar el teu joc?',
'Self publishing': 'Autopublicació',
'Social media promotion': 'Promoció a xarxes socials ',
'Video game journalists': 'Periodistes de videojocs ',
'Indie games streamers': 'Streamers de jocs indie',
'Events': 'Esdeveniments',
'Prizes': 'Premis',
'Looking for help?': 'Necesites ajuda?',
'Financing': 'Finançament',
'Associations': 'Associacions',
'Incubators': 'Incubadores',
'Publishers': 'Distribuïdors ',
'Student discounts': 'Descomptes per estudiants',
'Do you want to work on it?': 'Vols dedicarte a això?',
'Specialties': 'Especialitats',
'Education': 'Formació',
'Internship': 'Pràctiques',
'Jobs': 'Feina',
'Do you want to meet other people?': 'Vols conèixer altres persones?',
'Discord groups': 'Grups de Discord',
'Telegram groups': 'Grups de Telegram',
'Looking for inspiration?': 'Busques inspiració?',
'Books': 'Llibres',
'Podcasts': 'Podcasts',
'Documentaries': 'Documentals',
'Created by': 'Creat per',
'Did you find it useful?': 'T\'ha semblat útil?',
'Support project': 'Donar suport',
'Follow @StartGameDev': 'Seguir @StartGameDev',
'Buy a coffee': 'Convidar a un cafè',
'Share on Twitter': 'Compartir a Twitter',
'Name': 'Nom',
'Price': 'Preu',
'Editable list' : 'Llista editable',
'Information': 'Informació',
'List': 'Llista',
'Note: There are some affiliate links that will help me maintain the site at no cost to you.': 'Nota: Hi ha alguns enllaços d\'afiliat que m\'ajudaran a mantenir la web sense que et costi més',
'Forums': 'Fòrums',
'Topic': 'Temàtica',
'Year': 'Any',
'Duration': 'Duració',
'Location': 'Lloc',
'Month': 'Mes',
'Meetings': 'Reunions',
'Frequency': 'Freqüència',
'Fairs and conferences': 'Fires i conferències',
'Tools': 'Eines',
'Directory': 'Directori',
'Amount': 'Import',
'Requirements': 'Requisits',
'View price': 'Veure preu',
'Memory': 'Memòria',
'Resolution': 'Resolució',
'Buy': 'Comprar',
'Photo': 'Foto',
'PC required': 'Requereix PC',
'Store': 'Botiga',
'Mobile and tablets': 'Mòbils i tauletes',
'Account cost': 'Cost compte',
'Publish cost': 'Cost publicar',
'Platform cut': 'Cost venta',
'Consoles': 'Consoles',
'By contract cannot be published': 'Per contracte no es pot publicar',
'Not available, let me know if you have the data': 'No disponible, fes-m\'ho saber si tens la dada',
'Planning': 'Planificació',
'Documentation': 'Documentació',
'Share files': 'Compartir fitxers',
'Control version': 'Control de versions',
'Public Domain / Creative Commons / Free': 'De domini públic / Creative Commons / Gratis',
'Other licenses': 'Altres llicències',
'January': 'Gener',
'February': 'Febrer',
'March': 'Març',
'April': 'Abril',
'May': 'Maig',
'June': 'Juny',
'July': 'Juliol',
'August': 'Agost',
'September': 'Septembre',
'October': 'Octubre',
'November': 'Novembre',
'December': 'Desembre',
'Country': 'País',
'Monthly': 'Mensual',
'months': 'mesos',
'Interviews': 'Entrevistes',
'Monetization': 'Monetització',
'Multiplayer': 'Multijugador',
'Narrative': 'Narrativa',
'Fonts': 'Tipus de lletra',
'National': 'Nacional',
'Press kit examples': 'Exemples de Kit de premsa',
'Title': 'Títol',
'Author': 'Autor',
'Translators': 'Traductors',
};


// ITALIANO
i18n.it = 
{
'Gamedev Directory': 'Lista Gamedev',
'Home': 'Home',
'Support': 'Supportare',
'Contact': 'Contattare',
'Language': 'Lingua',
'Do you want to make a game?': 'Vuoi fare un videogioco?',
'Dictionary': 'Dizionario',
'Game engines': 'Motori',
'3D Models': 'Modelli 3D',
'Textures and materials': 'Texture e materiali',
'Music': 'Musica',
'Sounds': 'Suoni',
'Voice over': 'Locuzioni',
'Level design': 'Disegno di livelli',
'Interface': 'Interfacce',
'Virtual Reality': 'Realità Virtuale',
'Artificial inteligence': 'Intelligenza Artificiale',
'VFX and Shaders': 'VFX e Shaders',
'Organization': 'Organizzazione',
'Accesibility': 'Accessibilità',
'Do you want to promote your game?': '¿Vuoi promozionare il tuo gioco?',
'Self publishing': 'Autopubblicazione',
'Social media promotion': 'Promozione in social network',
'Video game journalists': 'Periodiste di videogioci',
'Indie games streamers': 'Streamer di gioci indie',
'Events': 'Eventi',
'Prizes': 'Premi',
'Looking for help?': 'Cerchi aiuto?',
'Financing': 'Finanziamento',
'Associations': 'Associaziones',
'Incubators': 'Incubatori',
'Publishers': 'Editori',
'Student discounts': 'Sconti studenti',
'Do you want to work on it?': 'Vuoi dedicarti a esso?',
'Specialties': 'Specialità',
'Education': 'Formazione',
'Internship': 'Pratiche',
'Jobs': 'Lavori',
'Do you want to meet other people?': 'Vuoi cognoscere altre persone?',
'Discord groups': 'Gruppi di Discord',
'Telegram groups': 'Gruppi di Telegram',
'Looking for inspiration?': 'Cerchi ispirazione?',
'Books': 'Libri',
'Podcasts': 'Podcasts',
'Documentaries': 'Documentali',
'Created by': 'Creato per',
'Did you find it useful?': 'Ti ha stato utile?',
'Support project': 'Supportare progetto',
'Follow @StartGameDev': 'Segui @StartGameDev',
'Buy a coffee': 'Invitare a un caffè',
'Share on Twitter': 'Compartire in Twitter',
'Name': 'Nome',
'Price': 'Prezo',
'Editable list' : 'Lista editabile',
'Information': 'Informazione',
'List': 'Lista',
'Online course': 'Corsi online',
'Note: There are some affiliate links that will help me maintain the site at no cost to you.': 'Nota: Ci sono qualcuni link di affgliato che mi aiuteranno a mantenere la web senza maggiore costo per te.',
'Forums': 'Fori',
'Topic': 'Tematica',
'Year': 'Anno',
'Duration': 'Durazione',
'Location': 'Luogo',
'Month': 'Mese',
'Meetings': 'Riunioni',
'Frequency': 'Frequenza',
'Fairs and conferences': 'Ferie e conferenze',
'Tools': 'Utensili',
'Directory': 'Lista',
'Amount': 'Importo',
'Requirements': 'Requisiti',
'View price': 'Guardare prezo',
'Memory': 'Memoria',
'Resolution': 'Risoluzione',
'Buy': 'Comprare',
'Photo': 'Foto',
'PC required': 'Richiede PC',
'Store': 'Magazzino',
'Mobile and tablets': 'Telefonini y tablet',
'Account cost': 'Costo conta',
'Publish cost': 'Costo pubblicare',
'Platform cut': 'Costo vendita',
'Consoles': 'Console',
'By contract cannot be published': 'Per contrato non si può pubblicare',
'Not available, let me know if you have the data': 'Non disponibile, facimi saperlo se hai il dato',
'Planification': 'Pianificazione',
'Documentation': 'Documentazione',
'Share files': 'Compartire file',
'Control version': 'Controle di versioni',
'Public Domain / Creative Commons / Free': 'Di pubblico dominio / Creative Commons / Gratis',
'Other licenses': 'Altre licenze',
'January': 'Genaio',
'February': 'Febraio',
'March': 'Marzo',
'April': 'Aprile',
'May': 'Maggio',
'June': 'Giugno',
'July': 'Giuglio',
'August': 'Agosto',
'September': 'Septembre',
'October': 'Ottobre',
'November': 'Novembre',
'December': 'Dicembre',
'Country': 'Paese',
'Monthly': 'Mensuale',
'months': 'mesi',
'Interviews': 'Interviste',
'Monetization': 'Monetizzazione',
'Multiplayer': 'Multigiocatore',
'Narrative': 'Narrativa',
'Fonts': 'Tipo di carattere',
'National': 'Nazionale',
'Press kit examples': 'Esempi di cartelle stampa',
'Title': 'Titolo',
'Author': 'Autore',
'Translators': 'Traduttori',
};

// PORTUGUÊS - BRASIL
i18n.br = 
{
'Gamedev Directory': 'Diretório Gamedev',
'Home': 'Início',
'Support': 'Apoiar',
'Contact': 'Entrar em contato',
'Language': 'Idioma',
'Do you want to make a game?': 'Quer fazer um jogo?',
'Dictionary': 'Dicionário',
'Game engines': 'Motores',
'3D Models': 'Modelos 3D',
'Textures and materials': 'Texturas e materiais',
'Music': 'Música',
'Sounds': 'Sons',
'Voice over': 'Locução',
'Level design': 'Design de níveis',
'Interface': 'Interfaces',
'Virtual Reality': 'Realidade Virtual',
'Artificial inteligence': 'Inteligência Artificial',
'VFX and Shaders': 'VFX e Shaders',
'Organization': 'Organização',
'Accesibility': 'Acessibilidade',
'Do you want to promote your game?': 'Quer promover seu jogo?',
'Self publishing': 'Autopublicação',
'Social media promotion': 'Promoção em redes sociais',
'Video game journalists': 'Jornalists de jogos',
'Indie games streamers': 'Streamers de jogos indie',
'Events': 'Eventos',
'Prizes': 'Prêmios',
'Looking for help?': 'Precisa de ajuda?',
'Financing': 'Financiamento',
'Associations': 'Associações',
'Incubators': 'Incubadoras',
'Publishers': 'Publishers',
'Student discounts': 'Descontos estudantis',
'Do you want to work on it?': 'Quer trabalhar nele?',
'Specialties': 'Especializações',
'Education': 'Formação',
'Internship': 'Estágio',
'Jobs': 'Empregos',
'Do you want to meet other people?': 'Quer conhecer outras pessoas?',
'Discord groups': 'Grupos de Discord',
'Telegram groups': 'Grupos de Telegram',
'Looking for inspiration?': 'Procurando inspiração?',
'Books': 'Livros',
'Podcasts': 'Podcasts',
'Documentaries': 'Documentários',
'Created by': 'Criado por',
'Did you find it useful?': 'Você achou útil?',
'Support project': 'Apoiar projeto',
'Follow @StartGameDev': 'Seguir @StartGameDev',
'Buy a coffee': 'Comprar um café',
'Share on Twitter': 'Compartilhar no Twitter',
'Name': 'Nome',
'Price': 'Preço',
'Editable list' : 'Lista editável',
'Information': 'Informação',
'List': 'Lista',
'Online course': 'Cursos online',
'Note: There are some affiliate links that will help me maintain the site at no cost to you.': 'Nota: Tem alguns links afiliados que me ajudarão a manter esse site de graça para você.',
'Forums': 'Forums',
'Topic': 'Tópico',
'Year': 'Ano',
'Duration': 'Duração',
'Location': 'Lugar',
'Month': 'Mês',
'Meetings': 'Reuniões',
'Frequency': 'Frequência',
'Fairs and conferences': 'Feiras e conferências',
'Tools': 'Ferramentas',
'Directory': 'Diretório',
'Amount': 'Quantidade',
'Requirements': 'Requisitos',
'View price': 'Ver preço',
'Memory': 'Memória',
'Resolution': 'Resolução',
'Buy': 'Comprar',
'Photo': 'Foto',
'PC required': 'Precisa de PC',
'Store': 'Loja',
'Mobile and tablets': 'Mobile e tablets',
'Account cost': 'Custo da conta',
'Publish cost': 'Custo da publisher',
'Platform cut': 'Corte da plataforma',
'Consoles': 'Consoles',
'By contract cannot be published': 'Por contrato não pode ser publicado',
'Not available, let me know if you have the data': 'Não disponível, me deixe saber quando você tem uma data',
'Planification': 'Planificação',
'Documentation': 'Documentação',
'Share files': 'Compartilhar arquivos',
'Control version': 'Controle de versões',
'Public Domain / Creative Commons / Free': 'Domínio Público / Creative Commons / Grátis',
'Other licenses': 'Outras licenças',
'January': 'Janeiro',
'February': 'Fevereiro',
'March': 'Março',
'April': 'Abril',
'May': 'Maio',
'June': 'Junho',
'July': 'Julho',
'August': 'Agosto',
'September': 'Setembro',
'October': 'Outubro',
'November': 'Novembro',
'December': 'Dezembro',
'Country': 'País',
'Monthly': 'Por mês',
'months': 'meses',
'Interviews': 'Entrevistas',
'Monetization': 'Monetização',
'Multiplayer': 'Multijogador',
'Narrative': 'Narrativa',
'Fonts': 'Fontes',
'National': 'Nacional',
'Press kit examples': 'Exemplos de kits de imprensa',
'Title': 'Título',
'Author': 'Autor',
'Translators': 'Tradutores',
};


